[package]
name = "truco-bot-core"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
smallvec = { version = "1.11", features = ["serde"] }
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
truco-engine.workspace = true
